version: '3.8'

services:
  vertu-algorithm-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REPO:-docker.vertu.com}/${APP_NAME:-faq_builder}:${VERSION:-1.0.0}
    container_name: faq_builder
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/vertu/src
      - /vertu/src/.venv
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
